name: Daily Paper Research Bot
on:
  schedule:
    - cron: '0 21 * * *' # 한국 시간 아침 6시 실행
  workflow_dispatch: # 수동 실행 버튼 활성화
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: 도구 설치
        run: pip install selenium webdriver-manager
      - name: 봇 실행
        run: python main.py
      - name: 결과 저장(Push)
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "오늘의 논문 업데이트" || echo "업데이트 없음"
          git push